project:
  type: website
  output-dir: docs

website:
  title: "Sehar Bajwa"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: uxresearch.pdf
        text: CV

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



